### ISSUE TITLE
Last spec for tictactoe

### ISSUE THREAD

**Issue by JVThomas** [learn-co-curriculum/js-tictactoe-rails-api#11]
Issue concenrs tictactoe.spec.js ln:433

Lack of stub for click event on ln:457 will cause test to fail. As it stands the test will click the button, but lack of a stubbed request/response cycle will leave the test with no data to update the board with. The result is a get request that will fail to execute since it'll request for a database entry that does not exist.

Suggested Solution:
```
     $('[data-gameid="2"]').click()
      
      var data = {
        game:{
          id:2,
          state: ["","X","O","","O","","","",""]
        }
      }

      var response = {
        "status": 200, 
        "contentType": 'application/json',
        "responseText" : JSON.stringify(data)
      }
      jasmine.Ajax.requests.mostRecent().respondWith(response);

     expect($('[data-x="0"][data-y="0"]').text()).toBe("")
     expect($('[data-x="1"][data-y="0"]').text()).toBe("X")
     expect($('[data-x="2"][data-y="0"]').text()).toBe("O")
     expect($('[data-x="1"][data-y="1"]').text()).toBe("O")
     ...
```

The added stub will provide the necessary data for student code to execute successfully (assuming no logical errors).

**Comment by AnnJohn** [comment]
thanks @JVThomas for raising this. We'll look into it soon.

**Comment by pletcher** [comment]
It looks like this is already mocked: https://github.com/learn-co-curriculum/js-tictactoe-rails-api/blob/master/spec/tictactoe.spec.js#L433 Is your fork up to date, @JVThomas?
