### ISSUE TITLE
Issue with active_model_serializers ver. 0.10.0

### ISSUE THREAD

**Issue by brennenawana** [learn-co-curriculum/js-tictactoe-rails-api#19]
Two Jasmine tests (described at the bottom) which deal with the game's persistence seem to be written assuming active_model_serializers ver. 0.9.4, which has a different JSON layout. This makes the Jasmine tests pass for one solution, even though it won't work in the browser, and it makes the other solution work in the browser, but not passing Jasmine tests. 
Here is an example:

**This is how the JSON looks with ver. 0.9.4**

![screenshot 2016-06-09 09 57 27](https://cloud.githubusercontent.com/assets/16592705/15932343/463e41dc-2e29-11e6-9830-dfad2ad56939.png)

**And this is how the JSON looks with ver. 0.10.0**

![screenshot 2016-06-09 09 59 04](https://cloud.githubusercontent.com/assets/16592705/15932361/662e3bfa-2e29-11e6-93b5-cc8dfd5dc6dc.png)

The two Jasmine tests (tictactoe.spec.js) are described as:
_"if i click the previous game button and no games have been saved i should get no games in the DOM"_
_"if i click the previous game button and a game has already been saved it should add the previous game to the DOM"_

**Comment by itzsaga** [comment]
This can be fixed by defining the gem version in your Gemfile if anyone else hits this:
`gem 'active_model_serializers', '0.9.4'`
