### ISSUE TITLE
Completion Checklist and Submit button error

### ISSUE THREAD

**Issue by ThisIsTyDell** [learn-co-curriculum/js-tictactoe-rails-api#20]
On the js-tictactoe-rails-api page, it will not allow to click "All Test Pass", "Handles Persistence", and "Submit". Unable to submit project. However I was able to run learn submit. Just not able to mark as complete on Learn.co site.

**Comment by gj** [comment]
Hi @ThisIsTyDell !

This wasn't an issue with the lab itself but rather with Learn.co. Best way to get timely help for non-curriculum issues is via [Ask a Question](help.learn.co/ask-a-question/how-to-ask-a-good-question), and the technical coaches can then escalate appropriately.

Either way, the issue should be fixed now. 🙂
