### ISSUE TITLE
Jasmine tests should be removed from this lab

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/js-tictactoe-rails-api#22]
Jasmine tests should be removed, OR labs should be re-written w/o jasmine tests (using mocha instead) and update in the Full Stack Web Dev. with React track.

@jmburges @Lukeghenco @cernanb

**Comment by DakotaLMartinez** [comment]
@aturkewi 

I was just working with Michael Djurdjevic. He can't even run any of the jasmine tests. When he runs `learn` they all fail. It seems like these tests can't run after we've removed the specRunner files. I don't see how these could possibly work. Seems like they have for a few people, but Michael wasn't able to get them running and I wasn't able to see how jasmine was even loaded into the project.

I saw the files in the spec/lib directory, but I didn't see them loaded into the specs anywhere. Any ideas what to do about this one?

**Comment by aturkewi** [comment]
This lab does not work on the IDE. Adding a note as a stop gap.
