### ISSUE TITLE
Make new Mocha tests less opinionated

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/js-tictactoe-rails-api#23]
Especially in advance of shift towards more OO JS concepts.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#33.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
