### ISSUE TITLE
Solution does not pass tests

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/js-tictactoe-rails-api#32]
I have been working through this lab with everything appearing to work in my browser just fine. The tests, however, were not passing. I contacted the tech coaches to help me understand the issues. They too were unable to explain why the tests were not passing when clearly my program was working as anticipated. When we put the solution into the editor and ran the tests it still did not pass. 

I'm not really sure why this is happening or what exactly is going on but the tests definitely need rewriting.

**Comment by FreeBreadsticks** [comment]
As an update to my previous issue. Changing the `const`to `var` for the win combos fixed the issue. Also, consider adding in a turn count function that literally counts the moves on the board. That's how I'd have the entire turn counter working if the tests didn't check for a set integer variable.  My Example : 
```
function turnCount() {
  counter = 0
  for (var i = 0; i < 9; i++) {
    if ($("td")[i].innerHTML === "X" || $("td")[i].innerHTML === "O") {
      counter++
    }
  }
  return counter
}
```

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#33 .  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
