### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/js-tictactoe-rails-api#33]
PROBLEM: Update solution. See issues #32, #25, #23, #29, #34 
NOTIFY: @gj, @FreeBreadsticks, @PCGeekBrain, @TheInvalidNonce

**Comment by PCGeekBrain** [comment]
Thank you for fixing this!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
