### ISSUE TITLE
Declaring a global turn variable with let causes tests to fail

### ISSUE THREAD

**Issue by TheInvalidNonce** [learn-co-curriculum/js-tictactoe-rails-api#34]
Using `let turn = 0` at the top of the lab causes tests to fail. I remedied this using `var turn = 0`.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#33.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
