### ISSUE TITLE
Mocha does not work in browser

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/js-tictactoe-rails-api#36]
When running `mocha.run()` in the console, I get the following error message:

```
Uncaught ReferenceError: mocha is not defined
    at <anonymous>:1:1
```

This makes the tests much harder to solve, since it prevents students from using `debugger` in the tests.

I ran `npm install` upon cloning the lab, and I see that `mocha` is listed as a dependency in `package.json`. I also see that the `tictactoeTest.js` is calling `mocha.setup('bdd');`, so I'm not sure why it's undefined in the console.

Reported by @vanetoro.

**Comment by d-d-d-dalia** [comment]
I have a student with this same issue today

**Comment by jd2rogers2** [comment]
same issue today too

changing `const`s in test file to `var`s allowed it to run in the browser

https://learn.co/tracks/full-stack-web-development-v6/rails-and-javascript/project-mode/jquery-tic-tac-toe-with-a-rails-api-part-2?batch_id=306&question_id=161138&track_id=43149

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
