### ISSUE TITLE
Test passing discrepancy between Mocha and NPM

### ISSUE THREAD

**Issue by kreopelle** [learn-co-curriculum/js-tictactoe-rails-api#37]
Throughout the lab, I had labs that passed in Mocha, but did not pass in npm. When I used Mocha to debug, the return values matched those in the test suite.

I am submitting this project with all of the Mocha tests passing, but could not re-work my code to get the final npm tests to pass.

The npm tests remaining were: 

1. Gameplay Users cannot place a token in a square that is already taken 

2. AJAX interactions with the Rails API Clicking a saved game button (in the div#games element) loads the saved game's state into the board

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
