### ISSUE TITLE
let turn not passing tests

### ISSUE THREAD

**Issue by PetyaDjanovska** [learn-co-curriculum/js-tictactoe-rails-api#38]
unable to pass the tests when using `let turn`. Tests require variable to be created as `var turn`.

**Comment by dannyenfp** [comment]
Same. Submitting with var.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
