### ISSUE TITLE
When Defining variables var will make the tests pass, but let and const wont make the test pass.

### ISSUE THREAD

**Issue by amckean12** [learn-co-curriculum/js-tictactoe-rails-api#39]
This passes 
`var turn = 0;

function player(){
  if(turn % 2 === 0){
    return 'X';
  }
  else{
    return 'O';
  }
}`

But this wont

`let turn = 0;

function player(){
  if(turn % 2 === 0){
    return 'X';
  }
  else{
    return 'O';
  }
}`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
