### ISSUE TITLE
Token with Vanilla JS

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/js-tictactoe-rails-api#40]
Lab says to use JQuery or VanillaJS - when using JQuery's `$.post()` to create a game, everything works fine but using `fetch()`, you have to add `<%= javascript_tag "window._token = '#{form_authenticity_token}'" %>` to `index.html.erb` and then set the following headers: `headers: {
            "Content-Type": "application/json",
            "Accept": "application/json",
            'X-CSRF-Token': window._token
        }`

The final `fetch` should look something like:
`fetch('/games', {
        method: "POST",
        body: JSON.stringify({
            state: translateState(),
            credentials: "same-origin"
        }),
        headers: {
            "Content-Type": "application/json",
            "Accept": "application/json",
            'X-CSRF-Token': window._token
        }
    })
    .then(res => res.json())
    .then(json => console.log(json))`

Seeing as the lab promotes being able to make it work with or without jQuery it may be a good idea to cover the basics of getting it to work without jQuery.

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
