### ISSUE TITLE
tictactoe.spec.rb:428  --id missing in test route

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/js-tictactoe-rails-api#7]
I may be wrong, but everything before line 428 (and line 249) make it seem like we're checking a 'PATCH' call, which requires a game id in the route. 

From the rake routes: `PATCH /games/:id(.:format) games#update`.

If that is right, line 428 should be:
```
      expect(request.url).toBe('/games/2');
```

**Comment by pletcher** [comment]
Both of those tests look okay to me. 

In the first case (lines 239 to 247), we're getting all of the games, so a GET request to `/games` seems sane.

In the second case, we're creating a new game, so we won't have its ID yet. So a POST to `/games` is appropriate here (as described in the test).
